### ISSUE TITLE
todo roadmap?

### ISSUE THREAD

**Issue by argais** [roboll/kube-vault-controller#7]
Heya, thanks for the great piece of software!

Just wanted to know if you have any roadmap for the token/approle support.

Cheers,

Fernando

**Comment by roboll** [comment]
Hey @argais - I haven't been touching this code much lately, so I don't have much of a roadmap.

I'd accept PRs for any of the items listed in the README (or other things if they make sense), so if you are up for putting together a PR I can help you out with anything you aren't sure of.

**Comment by argais** [comment]
Heya. Thanks for getting back to me. Unfortunately I didn't get past the
hello world in go yet :P maybe in the future :)
